// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8aKPZxibfbhmp-ZwzP3-O8xDuQw6aT9w',
    appId: '1:727901575736:web:7eddbd95be9b5380de24cd',
    messagingSenderId: '727901575736',
    projectId: 'evently-app-ec893',
    authDomain: 'evently-app-ec893.firebaseapp.com',
    storageBucket: 'evently-app-ec893.firebasestorage.app',
    measurementId: 'G-5QZSMNN5B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7VE3AjgoRqnIxreQueIMRsaZo1dWAnQ',
    appId: '1:727901575736:android:a80e86ffc19e000dde24cd',
    messagingSenderId: '727901575736',
    projectId: 'evently-app-ec893',
    storageBucket: 'evently-app-ec893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnBUyQQfg_0xAzI99rv1_0jnpYXlawUo',
    appId: '1:727901575736:ios:5a0522c777749a86de24cd',
    messagingSenderId: '727901575736',
    projectId: 'evently-app-ec893',
    storageBucket: 'evently-app-ec893.firebasestorage.app',
    iosBundleId: 'com.example.islami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADnBUyQQfg_0xAzI99rv1_0jnpYXlawUo',
    appId: '1:727901575736:ios:5a0522c777749a86de24cd',
    messagingSenderId: '727901575736',
    projectId: 'evently-app-ec893',
    storageBucket: 'evently-app-ec893.firebasestorage.app',
    iosBundleId: 'com.example.islami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8aKPZxibfbhmp-ZwzP3-O8xDuQw6aT9w',
    appId: '1:727901575736:web:d8598618b63a17a8de24cd',
    messagingSenderId: '727901575736',
    projectId: 'evently-app-ec893',
    authDomain: 'evently-app-ec893.firebaseapp.com',
    storageBucket: 'evently-app-ec893.firebasestorage.app',
    measurementId: 'G-2ZWD10S6V5',
  );
}
